### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#1]
Hi, I've just found your backup script which is now a fance package. Well done so far!
I've got some feedback which you might also apply to your software. If it gets enough votes on AUR I can also move this one to community. I'd love to do so ;)

* [x] No help message is available
* [x] The snapper configs to packup could be selectable via parameters: -c root home
* [x] or via a config setting in the snapper file itself. For example: `snapper get-config` `SNAP-SYNC_EXCLUDE=yes`
* [x] Readme typo: "Additionally you are **show** the location of the backed up snapshot."
* [x] "Enter name of directory to store backups:" should make more clear that this is a relative path and it does not need to exist: "Enter name of relative directory to store backups (created if not existing):"
* [x] Continue needs no "enter" only a "y". I personally do not like this behaviour.
* [x] A quiet `-q` option is missing.
* [x] Systemd timer for weekly/daily etc backups would be great.
* [x] An optional `-d --description` option could add additional description to the snapshot. For example `snap-sync weekly` with the timer above
* [x] Also copying the index file would be highly important to get the date of the snapshot
* [x] If you have multiple configurations and do the first time backup it prompts you for the path, backups the subvol and then asks for the path of the next config. All those setting should be askes first.

If you ask me in general I'd use the snapper config files itself for additional settings. I'd start with an initital config check, if new configuration (appart root etc) were found. Then snap-sync will configure those and start the backup afterwards. The quiet uption would skip the setting but possibly print a warning for a new (not backuped) config.

This tool is totally awesome and really essential for everyones snapper setup. Thanks a lot for sharing!

**Comment by NicoHood** [comment]
What I also noticed is that snap-sync does not work across network. I've mounted my backup share via sftp and obviously it does not show up. A remote connection would be highly appreciated.

**Comment by wesbarnett** [comment]
Wow! This is a lot of great feedback. It's going to take me a little bit to address the items, but I'll definitely go through your comments. Thanks!

**Comment by wesbarnett** [comment]
When you talk about the index file, do you mean "info.xml"? If so, that is being copied to the backup location.

**Comment by NicoHood** [comment]
@wesbarnett Yes i mean the info file. But the info file is not copied at the moment, as it is outside the btrfs subvolume. Please check that.

It would be nice if you can only check the boxes above which are implemented yet. That'd at least give you an better overview of the TODO and I can test that then. :)

**Comment by wesbarnett** [comment]
Considering the info file, snapper actually doesn't store the info file in the snapshot, but stores it at the same directory level as the snapshot.

I'm checking things off as I open up issues for them (or if its simple after I fix it), so it's easier to track, rather than tracking everything here in one thread. I'm going to close this thread and direct discussion on the other items to their issues (if not covered there, feel free to comment here or open another issue).

**Comment by NicoHood** [comment]
You could also consider to use the dbus interface of snapper which could provide a more relyable connection. However I personally have zero knowledge in that field.

If you also wish to have some help on some features or more opinions I can try to help. I've got tons of stuff to work on, but this one really interrests me.

**Comment by NicoHood** [comment]
Thank you for applying the changes so far. When do you plan the next release (cause I want to test the changes and do not want to create a -git package)?

**Comment by wesbarnett** [comment]
I plan on doing a release within the next day or so.

**Comment by NicoHood** [comment]
Thanks :)

Dont missunderstand my issue reports, I was just intensively searching for bugs. I love this script, that really solves tons of backup problems.

Edit: and it is extremely good that you sign your releases. That really improves the security of the package! Great step forward!

**Comment by NicoHood** [comment]
I just found this:
https://github.com/doudou/snapsync

I have not tried it at all, but maybe it could give you new ideas.

**Comment by NicoHood** [comment]
How do you sign the releases? Do you tag a release, download it and then sign it? Or do you rather use some internal git commands?

**Comment by wesbarnett** [comment]
Create the release on Github, download the tarball, and sign it. Then edit the release on Github and add an additional file, choosing the signature.

**Comment by NicoHood** [comment]
Alright. However you should still verify the content of the github download. But its extremely great that you do those steps, as it really helps to secure the archlinux system against software manipulations.
