### ISSUE TITLE
Can't Import the GPG Key

### ISSUE THREAD

**Issue by jwillikers** [wesbarnett/snap-sync#105]
Your link to the GPG key, https://barnett.science/public-key.asc, is inaccessible to me.
Firefox declares `Firefox can’t establish a connection to the server at barnett.science.`.
I'd like to import the GPG key to validate the archive.

**Comment by wesbarnett** [comment]
Oops, look like I took that site down. You can import via a public keyserver.

**Comment by jwillikers** [comment]
Do you have any recommendations on which public keyserver? I can't seem to find your email associated with the new key on `pool.sks-keyservers.net` or `keyserver.ubuntu.com`.

**Comment by wesbarnett** [comment]
Seems to be there: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf7b28c61944fe30dabeeb0b01070bcc98c18bd66

**Comment by jwillikers** [comment]
Sorry, must have just been me struggling with GPG.

```sh
➜ gpg --verify --auto-key-retrieve --keyserver keyserver.ubuntu.com ~/Downloads/snap-sync-*.tar.gz.sig
gpg: assuming signed data in '/home/jordan/Downloads/snap-sync-0.7.tar.gz'
gpg: Signature made Fri 29 Jan 2021 09:19:24 PM CST
gpg:                using EDDSA key F7B28C61944FE30DABEEB0B01070BCC98C18BD66
gpg: requesting key 1070BCC98C18BD66 from hkp server keyserver.ubuntu.com
gpg: key 1070BCC98C18BD66: 1 signature not checked due to a missing key
gpg: key 1070BCC98C18BD66: 3 signatures reordered
gpg: key 1070BCC98C18BD66: public key "Wes Barnett <wes@barnett.science>" imported
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Good signature from "Wes Barnett <wes@barnett.science>" [unknown]
gpg:                 aka "Wes Barnett <wes@wbarnett.us>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: F7B2 8C61 944F E30D ABEE  B0B0 1070 BCC9 8C18 BD66
```

I got it working, which completes my [blog post](https://www.jwillikers.com/backup-snapper-snapshots-with-snap-sync).
Thanks for snap-sync!
