### ISSUE TITLE
Archiving repository

### ISSUE THREAD

**Issue by wesbarnett** [wesbarnett/snap-sync#114]
Hi all, I can't keep up with the PR's and issues on this project. I no longer personally use btrfs and thus don't actively use this script myself, so troubleshooting issues and checking if new code works isn't possible. I'm opening this issue to notify the community that I'm going to be archiving this repository soon (date TBD), but the code will remain here on Github and be publicly accessible and fork-able for the community.

**Comment by NicoHood** [comment]
Nooo, it was such a good software!

Will you keep snap-pac?

**Comment by funcrab** [comment]
@wesbarnett 
> I'm just starting to learn Btrfs. Please let me know for reference.

What is the file system you are currently using?
I've just started learning Btrfs, but I'd like to consider it if there are other good file systems. It would be great if you could let me know for reference.
Sorry for getting off topic.

**Comment by wesbarnett** [comment]
> @wesbarnett 
> 
> > I'm just starting to learn Btrfs. Please let me know for reference.
> 
> 
> 
> What is the file system you are currently using?
> 
> I've just started learning Btrfs, but I'd like to consider it if there are other good file systems. It would be great if you could let me know for reference.
> 
> Sorry for getting off topic.

My personal machine was Btrfs but now I'm using a MacBook Air. I do have a personal server in the basement but am just using ext4 for that.

**Comment by funcrab** [comment]
> My personal machine was Btrfs but now I'm using a MacBook Air. I do have a personal server in the basement but am just using ext4 for that.

Thanks. So you didn't intentionally choose a better filesystem, especially compared to Btrfs?

**Comment by wesbarnett** [comment]
> Thanks. So you didn't intentionally choose a better filesystem, especially compared to Btrfs?

It depends on what you mean by "better". I chose ext4 for my server b/c it's more stable and I don't need snapshots. My MacBook Air obviously comes with APFS, so that was chosen for me.

Anyways, the point of this is that I'm not going to actively maintain this project any longer (I haven't really been active with it for quite some time anyways).

**Comment by funcrab** [comment]
I understand. Thank you for your time.

**Comment by NicoHood** [comment]
What about snap pac? You just did a whole rewrite in python lately!

**Comment by wesbarnett** [comment]
> What about snap pac? You just did a whole rewrite in python lately!

That one's not as hard to maintain - 0 issues and 0 PR's are open with it currently. It's pretty stable and I do have an old laptop with Btrfs/Arch if I need to ever troubleshoot it. The amount of time investment in that project is much less than this one though.

**Comment by bdaase** [comment]
What is your recommendation to use instead?

**Comment by wesbarnett** [comment]
> What is your recommendation to use instead?

I really don't have any. If this script works for you keep using it. But I can't support user requests, fix bugs, etc.

**Comment by baodrate** [comment]
FYI (leaving this here for posterity before the repo gets archived) I'll be maintaining a fork at https://github.com/qubidt/snap-sync

**Comment by NicoHood** [comment]
Before we switch to that fork, can't you two decide, if @qubidt gets write access to this repository? This would make it way easier for someone coming in via google, etc.

I can help with the PR reviews, if you like. But I won't write any code at the moment.

**Comment by wesbarnett** [comment]
@qubidt I would like to [transfer](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) this repository to you. When I initiate a transfer, it errors since you have a repository of the same name (since you have a fork).

**Comment by baodrate** [comment]
@wesbarnett I've renamed my fork so that should work now

**Comment by wesbarnett** [comment]
> @wesbarnett I've renamed my fork so that should work now

Transfer request sent. Thanks!

**Comment by baodrate** [comment]
Looks like it went through. Cheers!
