### ISSUE TITLE
Remote backups via ssh

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#12]
It would be nice to also backup data via ssh to a remote destination.

**Comment by wesbarnett** [comment]
I don't think `btrfs send | btrfs receive` works via ssh. At least I can't find anything on it.

**Comment by NicoHood** [comment]
I does work for sure. Some examples I found:
https://www.reddit.com/r/linux/comments/2e2iv0/confused_about_btrfs_incremental_remote_backups/
https://btrfs.wiki.kernel.org/index.php/Incremental_Backup

**Comment by wesbarnett** [comment]
Okay, I think this should be simple enough to implement, but it's going to be a while before I can get to it.

**Comment by wesbarnett** [comment]
I believe I've got this going on the master branch now. The only issue is that it requires the user to be able to login with "root" to the remote machine. I've tried using "sudo -t", etc, but that doesn't work being on the right side of a pipe (i.e., `btrfs send <args> | ssh -t sudo btrfs receive <args>`)

**Comment by wesbarnett** [comment]
I'm satisfied that this can be done as long as `root` is able to login on the remote machine. Security-wise, one should use a key and not permit password logins for `root`.

**Comment by NicoHood** [comment]
why wouldnt it work with sudo?

You could add some sample in the docs along with links how to use a key login rather than a password login.

Thanks for this feature, really great!

**Comment by wesbarnett** [comment]
When you run it as `sudo` that works fine. What I meant was that when you do, the `root` account on the remote machine needs to be able to login. You can't run `sudo` that requires a password on the remote machine due to the pipes (can never get a TTY when stdin being piped into ssh sudo from local machine). I'll add some info on using a key.
