### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#18]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures in order to verify easily and quickly of your source code releases.

**Overview of the required tasks:**
* [x] Please [create and/or use a 4096-bit RSA keypair](https://wiki.archlinux.org/index.php/GnuPG#Create_key_pair) for the file signing
* The key may be used for [email encryption](https://www.enigmail.net/index.php/en/) too
* Keep your key secret, use a strong unique passphrase for the key
* [x] Upload the public key to a key server
* [x] [Sign every new commit by default](https://help.github.com/articles/signing-commits-using-gpg/)
* [x] [Sign new tags](https://help.github.com/articles/signing-tags-using-gpg/)
* Verify the Github Release tarball download against your local source
* [x] [Sign Github Release tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)

**Additional Information:**
* https://help.github.com/categories/gpg/
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

Thanks.

**Comment by wesbarnett** [comment]
Is this an official policy for Arch Linux?

**Comment by NicoHood** [comment]
No, not yet. You already did a great job in signing the releases yourself, however I noticed your commits are not yet signed, so I wanted to point this out.

If you ask me every package for archlinux should use gpg signatures (for release and source). I will propose a mail about that for the mailing list possibly soon.

**Comment by wesbarnett** [comment]
Any suggestions on an easy way to compare the Github generated tarball and my local source? pkgdiff seems to work for now.

**Comment by NicoHood** [comment]
what do you mean by pkgdiff?

The safest way would be to create your own tar, especially with xz -9 to get the best compression possible. This way you can ensure what is inside the package, but it also wastes some of the githubs storage (if we'd care).

Similar to this software:
https://github.com/mhogomchungu/zuluCrypt/releases

I currently also search for solutions to automate this process.

**Comment by wesbarnett** [comment]
Gotcha. So I've been depending on Github's release's feature, but it looks like I'd just have to add another tarball to the release.

**Comment by NicoHood** [comment]
Well it would make sense to use their tarball, but you'd have to verify it and that is not that simple. Also .xz gives us better compression (please use -9) so that should be fine. However we should exclude the files that .gitignore does not track or are not added to the git yet. This might be relevant for bigger projects, also with a build directory. If you have any ideas about that let me know.

**Comment by wesbarnett** [comment]
Right, I forgot to mention, that's what I was using pkgdiff for. pkgdiff compares the contents of two tarballs. It's in the repos.

**Comment by NicoHood** [comment]
You can use this script to create signed, tagged releases now:
https://github.com/NicoHood/NicoHood.github.io/wiki/Github-GPG-signed-release-script

It is still under development but contains everything you essentially need to sign packages.

**pkgdiff is highly risky as it only checks the filenames, not the content.** the whole .tar.gz needs to be identical. Dont use hashes, compare with cmp directly.

**Comment by NicoHood** [comment]
The script is way better now and can be found here:
https://github.com/NicoHood/gpgit

Thanks for using GPG signatures!
