### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#20]
It would be nice to get a notification when the service wants to do a backup. Also it would be nice to add a notification of the backup finished. I've seen examples in bach which are extremely simpler to integrate into libnotify. I can imagine notifications like this:
* "Backing up configuration xyz"
* "Please mount partition xyz for snap-sync backup"
* "Backup of configuration xyz finished"

**Comment by wesbarnett** [comment]
I've been looking into this. The issue I'm running into is that the script needs to be run as root (and thus the systemd service is run as root), so pushing the notifications to the regular user can get unwieldy Still investigating..

**Comment by NicoHood** [comment]
If i am not wrong you can grant users access to use snapper with user privileges. If you do not need to use pure btrfs commands or anything else that requires root access, we could run the script as user for those subvolumes that the user has access to.

btw: the index.xml file is root:root. I already opened an issue at the snapper bugtracker some month ago. So currently it wont be possible to run snap-sync in user mode anyways.

Onother idea would be a sudo wrapper/recognizer. Because you can recognize if sudo is used and then execute back the commands as normal user. This might be the best idea. This would then only work on normal/manual backup, which is okay for me.

**Comment by wesbarnett** [comment]
I think the latest commits satisfy this.
