### ISSUE TITLE
Corruption prevention/log

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#22]
I just started your tool for my root partition and the shell with the command disappeared (I possibly closed it). I dont know if the backup finished or not. And if it was not finished I am asking myself if snap-sync can detect it, to not produce more corrupted backups.

A logfile of the output would be nice. /var/log/snap-sync maybe. I did not run it as a service.

A detection if more than 2 snap-sync snapshots exist would be nice. the new one was possibly not transmitted correct. --> I checked what happens and it seems that it leaves the corrupted one, because its not tagged:
```
single | 2450 |       | Fri 23 Dec 2016 09:00:05 PM CET  | root | timeline | timeline                                                  |                                                                 
single | 2451 |       | Fri 23 Dec 2016 10:00:05 PM CET  | root | timeline | timeline                                                  |                                                                 
single | 2452 |       | Fri 23 Dec 2016 10:00:10 PM CET  | root |          |                                                           | 
```

The problem with this is, that this is never cleaned up. So a tag like "backup_inprogress" would be a way to indicate failed backups. Next time snap-sync can detect this, warn and ask for deletion.

Edit:
Got config in use again after i try to transfer again:
```
Will backup //.snapshots/2474/snapshot to /run/media/arch/e5b8a2d6-85a1-4640-a659-acb8d6922bd6/backup/E744/root/2474//snapshot
Continue with backup [Y/n]? y
At subvol //.snapshots/2474/snapshot
Config is in use.
```

**Comment by wesbarnett** [comment]
Good idea about the logging. (cf #21)

**Comment by wesbarnett** [comment]
I think this is fixed given these commits. Closing.

**Comment by NicoHood** [comment]
If the script starts it should check for existing "in progress" snapshots and ask for deletion of those. or warn at least. i think that is missing currently.

**Comment by wesbarnett** [comment]
Closing in favor of #24
