### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#23]
Your key expired as you can see in this commit:
https://github.com/wesbarnett/snap-sync/commit/01b7237e111aa19d921fb43fd2436e05a70ac40c

You need to update it, publish it to the keyservers and possibly update the github profile. But i would not edit the github profile unless you need to. Otherwise it could make every commit so far unverified again (permanently). At least thats what i remember from the docs.

**Comment by wesbarnett** [comment]
It wasn't expired (I renewed in Jan). I had to delete the key from Github and re-add for it to recognize it, but its fixed now
