### ISSUE TITLE
Exclude source btrfs subvolumes

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#28]
It would be nice to exclude the subvolumes that the system is installed on, so you get less entries. For me those are by default min 11 which could be reduced. You can identify them by uuid I think.

**Comment by wesbarnett** [comment]
How about a variable you set in a file like `/etc/snap-sync.conf` where you can exclude a UUID from the menu?

**Comment by NicoHood** [comment]
Nah. I would exclude the uuids/pathes that are being backed up. Theoretically you could backup to the same disk but that would absolutely not make any sense.

```
[arch@arch ~]$ findmnt -n -v -t btrfs -o UUID --list
c91384af-f210-48f5-ba19-d6415a1bb447
c91384af-f210-48f5-ba19-d6415a1bb447
c91384af-f210-48f5-ba19-d6415a1bb447
c91384af-f210-48f5-ba19-d6415a1bb447
c91384af-f210-48f5-ba19-d6415a1bb447
c91384af-f210-48f5-ba19-d6415a1bb447
c91384af-f210-48f5-ba19-d6415a1bb447
c91384af-f210-48f5-ba19-d6415a1bb447
c91384af-f210-48f5-ba19-d6415a1bb447
c91384af-f210-48f5-ba19-d6415a1bb447
c91384af-f210-48f5-ba19-d6415a1bb447
[arch@arch ~]$ findmnt -n -v -t btrfs -o TARGET --list
/
/var/tmp
/var/abs
/home
/hackallthethings
/srv
/.snapshots
/data
/var/log
/var/cache/pacman/pkg
/home/arch/.local/share/Steam
```

So I'd do it like this:
1. Select configs to backup (source)
2. Select destination btrfs filesystem (exclude source filesystems)
3. Start backup

I know that this needs some internal changes of the script, but it would make more sense. This way you can also easily fail if no backup media is connected.


Edit: The exclude option could still be a nice idea. Make sure to add it to the docs, if not done yet.
