### ISSUE TITLE
Add option to verify backup

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#29]
Wouldnt it be possible to cmp both subvolumes after the sync? If btrfs send outputs the exact same output for src and dest the backup is okay. However I am not sure if btrfs send always work the same (same order of files). If not maybe there is another way to verify the backup?

**Comment by wesbarnett** [comment]
Idea for implementing this:
https://serverfault.com/questions/399894/does-btrfs-have-an-efficient-way-to-compare-snapshots

Perhaps using send to create a file on the first snapshot. Then using send to create a file on the received snapshot and diffing those files.

    btrfs send --no-data /.snapshots/5816/snapshot -f snap1
    btrfs send --no-data /mnt/acer-c720/root/5816/snapshot -f snap2
    diff snap1 snap2

**Comment by wesbarnett** [comment]
https://github.com/sysnux/btrfs-snapshots-diff/blob/master/btrfs-snapshots-diff.py

**Comment by NicoHood** [comment]
can't we optdepend on this software and use it if installed? Or maybe just fork it.

**Comment by wesbarnett** [comment]
It doesn't seem like that software is going to work for this. Even if the data is exactly the same, the metadata is going to be different.

**Comment by wesbarnett** [comment]
Closing. Last discussion was a few years ago.
