### ISSUE TITLE
shellcheck linting

### ISSUE THREAD

**Issue by kalbasit** [wesbarnett/snap-sync#35]
I use [shellcheck](https://github.com/koalaman/shellcheck) myself for all of my scripts, it helps avoid common bash mistakes, I also have it integrated with Travis for my projects. @wesbarnett would you accept a PR with shellcheck changes integrated and a `.travis.yml` to have it checked?

**Comment by wesbarnett** [comment]
I can see there are several improvements to be made using shellcheck as a guide (as well as some bad coding of mine that needs to be fixed), but I'm unsure of automation. I'll look over it some.

**Comment by wesbarnett** [comment]
Not going to implement for now. Thanks.
