### ISSUE TITLE
Use upstream's location for configuration file

### ISSUE THREAD

**Issue by wesbarnett** [wesbarnett/snap-sync#43]
Other distributions follow upstream's location of `/etc/sysconfig/snapper`. Also add an installation flag of some sort to change this location (e.g., for Arch it would be `/etc/conf.d/snapper`). Then for Arch the flag could be used with the AUR package.

cf. #42

**Comment by rralf** [comment]
EXCLUDE_UUID=$(findmnt -n -v -t btrfs --target $SNAPPER_CONFIG -o UUID)

will fail, if /etc/ is no btrfs (in my case, / is ext4):

Exited due to error on line 167.
exit status: 1
command: EXCLUDE_UUID=$(findmnt -n -v -t btrfs --target $SNAPPER_CONFIG -o UUID)
bash line: 0
function name: main

**Comment by wesbarnett** [comment]
@rralf Issue #44 opened.
