### ISSUE TITLE
Support --noconfirm with btrfs disks with that have been mounted in multiple locations

### ISSUE THREAD

**Issue by sirkcion** [wesbarnett/snap-sync#45]
The systemd service errors out when multiple mount points are found with the same UUID as it prompts user to select mounted btrfs device option. Backup disk has a / and /.snapshots subvolumes with the same UUID.

**Comment by wesbarnett** [comment]
Can you give me the exact error message?

**Comment by wesbarnett** [comment]
Nevermind, I see the issue. I'm not sure I know what the solution is yet though.

**Comment by wesbarnett** [comment]
I've removed the systemd service file, but I have provided examples in the README. It becomes a pain to have to pass two arguments to a systemd service, although it is possible. The underlying problem, of not being able to use `--noconfirm` with a disk that has been mounted multiple times has been fixed.
