### ISSUE TITLE
Perform all user prompts at beginning of script

### ISSUE THREAD

**Issue by wesbarnett** [wesbarnett/snap-sync#5]
See #1.

**Comment by NicoHood** [comment]
This does not work for me:
```
[arch@arch snap-sync]$ sudo snap-sync
Select a mounted BTRFS device to backup to.
   1) c91384af-f210-48f5-ba19-d6415a1bb447 (/)
   2) c91384af-f210-48f5-ba19-d6415a1bb447 (/var/cache/pacman/pkg)
   3) c91384af-f210-48f5-ba19-d6415a1bb447 (/var/tmp)
   4) c91384af-f210-48f5-ba19-d6415a1bb447 (/srv)
   5) c91384af-f210-48f5-ba19-d6415a1bb447 (/data)
   6) c91384af-f210-48f5-ba19-d6415a1bb447 (/hackallthethings)
   7) c91384af-f210-48f5-ba19-d6415a1bb447 (/var/log)
   8) c91384af-f210-48f5-ba19-d6415a1bb447 (/home)
   9) c91384af-f210-48f5-ba19-d6415a1bb447 (/.snapshots)
  10) c91384af-f210-48f5-ba19-d6415a1bb447 (/var/abs)
  11) c91384af-f210-48f5-ba19-d6415a1bb447 (/home/arch/.local/share/Steam)
  12) e5b8a2d6-85a1-4640-a659-acb8d6922bd6 (/run/media/arch/e5b8a2d6-85a1-4640-a659-acb8d6922bd6)
   0) Exit
Enter a number: 12

You selected the disk with UUID e5b8a2d6-85a1-4640-a659-acb8d6922bd6.
The disk is mounted at /run/media/arch/e5b8a2d6-85a1-4640-a659-acb8d6922bd6.

Creating new snapshot for root...
Will backup //.snapshots/3109/snapshot to /run/media/arch/e5b8a2d6-85a1-4640-a659-acb8d6922bd6/backup/E744/root/3109//snapshot
Continue with backup [Y/n]? 
Select 'Y' or 'n'.
Continue with backup [Y/n]? y
Sending incremental snapshot for root...
At subvol //.snapshots/3109/snapshot
Deleting old snapshot for root...
Config is in use.
```

I expect the script to ask for root, then home and then continue with the actual backup. Furthermore `enter` should trigger the default option Y (thats why its capital) and dont ask again.

What happens for me is that it only backs up root and not home and hackallthethings configs. Also the config in use #21 bug is triggered again for me. I am on a fresh boot currently.

**Comment by wesbarnett** [comment]
I personally like the confirmation prompt to be just before the backup is made. To skip all the confirmations you can just use `--noconfirm`.

Regarding the `Config is in use`, I cannot reproduce it. It's unable to delete the old local snapshot. My suggestion would be to try to do an incremental send manually (make a local btrfs snapshot, send it to an external drive, do some things (just to change the data), make a new local btrfs snapshot, send the incremental difference between the old and new local snapshots to the external drive, delete the old local snapshot.) That would help to debug this issue.

**Comment by NicoHood** [comment]
The problem i am facing here is that the config `home` and `hackallthethings` are ignored. Only root is being backed up now.

Config in use is another issue. I have no idea, but that is just "also" annoying.

**Comment by wesbarnett** [comment]
Can you post the relevant log to #26? Just opened it regarding it ignoring some configurations. Also post the result from `ls /etc/snapper/configs` and the contents of the `home` and `hackallthethings` snapper configuration files.
