### ISSUE TITLE
Don't delete old snapshot when transfer failed

### ISSUE THREAD

**Issue by daphee** [wesbarnett/snap-sync#51]
I currently had my incremental backup fail because the target disk was full. Snap-sync logged the error but still deleted the old snapshot which made me do a full backup again.

**Comment by wesbarnett** [comment]
Definitely a bug and not intended. I will look into it.

**Comment by wesbarnett** [comment]
This error should be trapped now before the next command (the snapshot deletion) is executed. If you re-encounter this errror, please re-open.
