### ISSUE TITLE
does this only sync incremental snapshots?

### ISSUE THREAD

**Issue by ghost** [wesbarnett/snap-sync#52]
thereby defeating the purpose? for example if my local drive gets hosed, what is the use-case of externally-backed incremental snapshots?

or is my understanding flawed?

**Comment by wesbarnett** [comment]
Defeat the purpose in what way? Are you asking if you have to go through all the snapshots and copy them back when restoring? When restoring a system you would just copy over the data from the latest snapshot.

**Comment by ghost** [comment]
restoring from what state? would the system be restorable from an empty
state, if for example the drive was replaced?

my assumption is the reason we make backups is in a case of catastrophic
loss. btrfs send and receive creates a bootable snapshot from a clean slate
to an external target and then incrementally saves changes. i’m just
curious if snap-sync is only intended as a system rollback tool provided
system integrity is assured or if it also allows full system restore from a
catastrophic scenario.

**Comment by wesbarnett** [comment]
Depends on what subvolumes you back up. I have my root subvolume separated from my home subvolume, so they are backed up separately. Additionally snapshots exclude subvolumes that are nested below them. If you had your root subvolume backed up and you replaced your computer's drive, you could use a live disk to copy over (via snapshotting or whatever method) the system from the backup.

**Comment by wesbarnett** [comment]
Closing this out. If my answer is not satisfactory, feel free to re-open.
