### ISSUE TITLE
Use Readline to obtain the line in an interactive shell

### ISSUE THREAD

**Issue by AtosNicoS** [wesbarnett/snap-sync#60]
When you start your new backups:
```
Enter name of directory to store backups, relative to /run/media/<path> (to be created if not existing):
```

If you enter for example "baackup" and want to press the left arrow key it will add some "baackup^[[D". If you use `read -e` this error will be gone. Conside to use this on all interactive read operations.

**Comment by wesbarnett** [comment]
Nice catch.
