### ISSUE TITLE
Allow non-root user to run script

### ISSUE THREAD

**Issue by wesbarnett** [wesbarnett/snap-sync#63]
This is especially important for sending snapshots via ssh, since allowing the `root` user to login via ssh is bad practice. Snapper has the ability to allow regular users to use the configurations if permissions are set correctly.

**Comment by NicoHood** [comment]
Not only ssh, but what about local snapshots? This is still not supported, right? As you need btrfs send as sudo command and this would leak the data of every btrfs filesystem. For security purposes I would not add this to the sudo list.

**Comment by wesbarnett** [comment]
I don't think there's a way to do this, since root is required.
