### ISSUE TITLE
Crash on deleting failed backup

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#66]
I ran snap-sync on a new disk. I set the path for some configurations (home included), but then noticed I used a wrong path and aborted using CTRL+C. I ran the script again and confirmed to delete the home config, but the script failed:

```
NOTE: Previous failed snap-sync backup snapshots found for 'home'.
Delete failed backup snapshots [y/N]? y
Invalid snapshot 'single'.
Exited due to error on line 308.
exit status: 1
command: snapper -c $x delete $(snapper -c $x list | awk '/'$name' backup in progress/ {print $3}')
bash line: 0
function name: main
```

**Comment by NicoHood** [comment]
Is it possible because snapper changed the columns of the snapper list output? $1 could work maybe?

**Comment by NicoHood** [comment]
$1 works.

**Comment by NicoHood** [comment]
You should check if nothing else in the script is affected. I only saw one more snapper list command, this already uses $1. But this commit is even older, so I am wondering why this bug came up now and not earlier. I might miss something, so please have a look carefully.

**Comment by phw** [comment]
I can confirm the issue and the fix

**Comment by NicoHood** [comment]
Would you mind tagging a new bugfix release for this?

**Comment by wesbarnett** [comment]
Sure. Probably this weekend.
