### ISSUE TITLE
Snapshots of multiple volumes will all fail if there is an error on the first one.

### ISSUE THREAD

**Issue by R1dO** [wesbarnett/snap-sync#69]
Related to #68 

If using multiple snapper configurations they will all fail when the first one fails due to an error on line 458
```btrfs send -c "$old_snap" "$new_snap" | $ssh btrfs receive "$backup_location" ```.

Manually skipping the erroneous configuration allows the remainder to perform a successful backup.

**Comment by wesbarnett** [comment]
I understand your point of view here. However, I think it is safer behavior for the entire script to fail if any single backup fails. I imagine continuing on would allow the script to exit successfully with silent failures.
