### ISSUE TITLE
snap-sync does not ask for deleting old snapshots anymore

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#74]
I dont know why yet, but the feature to remove old snapshots does not work anymore. snap-sync does not delete its snapshot on a succesful run, and it also does not detect, that there are old snapshots that may be deleted now. This might be caused by a snapper or btrfs update?

Snapshots left after sync:
```
3271  | single |       | Sun 26 Jan 2020 11:00:28 AM CET  | root | number   | old snap-sync snapshot (you may remove)                                     |                                                                                 
```

As you can see the userdata is missing and thatswhy it does not get detected nor deleted?

It seems the old snapshot gets renamed and all userdata cleared. So it cannot be detected and deleted again. But why?
https://github.com/wesbarnett/snap-sync/blob/master/bin/snap-sync#L455

**Comment by NicoHood** [comment]
It seems the error was introduced with version 0.5. It does not delete snapshots at all anymore, just modify them.
https://github.com/wesbarnett/snap-sync/commit/34ef2fa18528caa8b9fc2acc33e6344606077f5e#diff-524d0b02cac6aa94ab773784170bbbd0

It seems the internal snapper cleanup is used to cleanup those snapshots. You may want to add a note to the user at the end of the script to manually run that cleanup service:
```
sudo systemctl start snapper-cleanup.service
```

Also this caused some trouble for me, as I normally do not use numbered snapshots on all snapper configs. This means it will keep 50(!) additional very old snapshot using the "number" cleanup algorithm - that is the default setting.

**Comment by cmonty14** [comment]
I would prefer that snap-sync deletes the old snapshots, because snapper functionality for cleanup depends on quota enabled and this can cause slowdowns (see [here](https://www.reddit.com/r/btrfs/comments/fmucrq/btrfs_snapshots_make_entire_system_lag_cpu_usage/) and [here](https://wiki.archlinux.org/index.php/Snapper#Cleanup_based_on_disk_usage)).
