### ISSUE TITLE
Snapshot size indicates: there's no incremental backup

### ISSUE THREAD

**Issue by cmonty14** [wesbarnett/snap-sync#78]
Hi,
after setting up snap-sync for all OS relevant subvolumes (this is SLES 12SP4) I created two backups:
- initial backup
- 2nd backup one week later

My expectation is that the 2nd backup is incremental and only includes the changes compared to initial backup.
Then I checked the size of each subvolume using [this](https://poisonpacket.wordpress.com/2015/05/26/btrfs-snapshot-size-disk-usage/) script.

Filtering the output to only 1 subvolume shows: the size of each snapshot is (more or less) equal.
```
vlcdbs1p:/backup_rbd_lve_os # btrfs-size | grep opt
@/opt                                                                                                            575.55MB   263
@/var/opt                                                                                                         16.00KB   277
@/opt/.snapshots                                                                                                  16.00KB   478
@/opt/.snapshots/1/snapshot                                                                                      559.59MB   489
@/opt/.snapshots/2/snapshot                                                                                      575.46MB   503
```

Based on these figures I assume that the allocated disk space increases for each backup by the current size of the subvolume. But this is not an incremental backup in my understanding. And it means that I must calculate much more disk space to be reserved for my backup strategy.

Please share your thoughts on this.

THX

**Comment by wesbarnett** [comment]
I'm not familiar with that script, but in my experience incremental backups are working.

A quick way to check is to measure how much space is taken before the first backup, after the first backup, and then after the second backup. From my experience the second backup is much faster. Additionally when I backup 100G the first backup fills up an additional 100G, but after the second backup the disk is not 200G full, which it would be if it wasn't incremental.

**Comment by wesbarnett** [comment]
@cmonty14 any info on whether or not this incremental test as described above works? I don't see any issues here.

**Comment by NicoHood** [comment]
That is not true. Just do a backup and then do a backup again. You will see, that the second backup will be almost instantly, as there is no more diff to transfer. On the disk it will look like the data is duplicated, but that is handled by btrfs internally.

I guess this can be closed now.
