### ISSUE TITLE
Restore failure: ERROR: failed to get flags for subvolume 

### ISSUE THREAD

**Issue by cmonty14** [wesbarnett/snap-sync#83]
Hello,

I have setup snap-sync to create weekly backups of several subvolumes.

Now I need to restore the backups after the server has been destroyed.
All backups are located on central storage and the remote drive is mounted to the server.

When I execute this command it ends with failure:
```
ld4759:~ # btrfs send /backup_rbd_lve_os/ld4759/home/37 | btrfs receive /home/.snapshots/
ERROR: failed to get flags for subvolume /backup_rbd_lve_os/ld4759/home/37: Invalid argument
```

The available backups on the central storage are here:
```
ld4759:~ # ls -l /backup_rbd_lve_os/ld4759/home/
total 0
drwxr-xr-x 1 root root 32 Jun 18 10:24 1
drwxr-xr-x 1 root root 32 Jun 22 00:00 29
drwxr-xr-x 1 root root 32 Jun 29 00:00 30
drwxr-xr-x 1 root root 32 Jul  6 00:00 31
drwxr-xr-x 1 root root 32 Jul 13 00:00 32
drwxr-xr-x 1 root root 32 Jul 20 00:00 33
drwxr-xr-x 1 root root 32 Jul 27 00:00 34
drwxr-xr-x 1 root root 32 Aug  3 00:00 35
drwxr-xr-x 1 root root 32 Aug 10 00:01 36
drwxr-xr-x 1 root root 32 Aug 17 00:00 37
```

What's causing this failure?
What's the correct procedure for restoring set of incremental backups?
What must be considered when restoring root subvolume?

THX

**Comment by wesbarnett** [comment]
Double check the paths that they are indeed a subvolume. The backup should have a directory in it named "snapshot" which is the subvolume.
