### ISSUE TITLE
Fedora RPMBuild/COPR support

### ISSUE THREAD

**Issue by brndd** [wesbarnett/snap-sync#88]
Hey, I'm not sure if packaging for distros other than Arch is something you care about doing at all, but I created a .spec file for packaging this into RPM a few months ago and figured I'd put it here. https://gist.github.com/brndd/def97361f00e264843e0258633bb44ee

I used this specfile to create a [COPR build](https://copr.fedorainfracloud.org/coprs/peoinas/snap-sync/) of snap-sync, COPR being the AUR equivalent of RPM-based distros, making it a little easier to install on supported distros.

Right now the COPR build is manual. With some extra effort the COPR builds could be automated whenever there is a new release of snap-sync on Github. As I understand it the extra legwork is stuff the maintainer has to do, mostly because of webhook things; see [this blog post](https://hobo.house/2017/09/03/automate-rpm-builds-from-git-sources-using-copr/) for more details if you're interested.

**Comment by bdaase** [comment]
Just wanted to leave my appreciation here, that you created and maintain this copr. This makes things way easier!

**Comment by wesbarnett** [comment]
Hi @brndd thanks so much for the contribution. Happy to see others are using this script.  I will link to your gist on the README.
