### ISSUE TITLE
GPG Signature issue for 0.7 release

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#98]
Hi Wes,
the signature for the 0.7 release includes the release itself.

```
$ gpg --verify snap-sync-0.7.tar.gz.sig 
gpg: Signature made Sun 24 Jan 2021 01:36:39 PM CET
gpg:                using EDDSA key F7B28C61944FE30DABEEB0B01070BCC98C18BD66
gpg: Good signature from "Wes Barnett <wes@barnett.science>" [unknown]
gpg:                 aka "Wes Barnett <wes@wbarnett.us>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: F7B2 8C61 944F E30D ABEE  B0B0 1070 BCC9 8C18 BD66
gpg: WARNING: not a detached signature; file 'snap-sync-0.7.tar.gz' was NOT verified!
```

It would be best to use a detached signature ascii encoded instead:
```
gpg2 --digest-algo SHA512 --armor --detach-sign snap-sync-0.7.tar.gz
```

FYI: You can automate the process using GPGit if you like. I've recently added an automation for GPGit that pulls in your [changelog to the Github release](https://github.com/NicoHood/gpgit/releases/tag/1.4.0), maybe that can help you.

Also thanks for adding me as co-maintainer! :-)

**Comment by wesbarnett** [comment]
Thanks! I've updated the release with a new signature. It's been quite some time since signing a release :)

**Comment by NicoHood** [comment]
Thanks! It works now!
